# ============================================================ #
#           Configuration for VypnitoCombat Plugin             #
# ============================================================ #

# --- Global PvP Settings ---
global_pvp_enabled: true

# --- Protections for when Global PvP is Disabled ---
pvp_protections:
  prevent_lava_placement_near_players: true
  lava_check_radius: 3
  prevent_harmful_splash_potions: true
  harmful_potion_effects:
    - HARM
    - POISON
    - SLOWNESS
    - WEAKNESS
    - WITHER

# --- Core Combat Settings ---
combat_duration_seconds: 10
action_bar_timer: true
end_combat_on_death: true

# --- Custom Death Message ---
death_messages:
  use_custom_when_in_combat: false

# --- Region Protections (Requires WorldGuard) ---
region_protections:
  prevent_safe_zone_entry_in_combat: true
  pushback_strength: 0.8

# --- In-Combat Restrictions ---
combat_restrictions:
  block_riptide: true
  # DANGEROUS: If true, instantly sets an equipped elytra's durability to 1 when a player
  # enters combat or an elytra cooldown period. This is effective but punitive.
  damage_elytra_on_restrict: true
  blocked_items_in_combat:
    - ELYTRA # This now primarily blocks firework boosting
  blocked_commands_in_combat:
    - "home"
    - "spawn"
    - "tpa"
    - "warp"

# --- Cooldowns After Combat ---
cooldowns_after_combat:
  elytra_seconds: 20
  ender_pearl_seconds: 15

# --- Punishments for Combat Logging ---
punishments:
  kill_player: true
  execute_commands:
    - "broadcast &c%player% combat logged and was punished!"

# --- Integrations ---
integrations:
  worldguard:
    enabled: true